[package]
name = "sapper_logger"
version = "0.1.0"
authors = ["Mike Tang <miketang84@outlook.com>"]
license = "MIT"
description = "Basic logger module for sapper web framework."

[dependencies]
sapper = "0.1"
time = "0.1.37"
log = "0.3.7"

