[package]
name = "sapper_logger"
version = "0.1.0"
authors = ["Mike Tang <miketang84@outlook.com>"]

[dependencies]
sapper = { git="https://github.com/sappworks/sapper" }
time = "0.1.37"
log = "0.3.7"

